"""add logos model

Revision ID: 985534b682db
Revises: f1d75244863f
Create Date: 2023-11-22 13:35:20.368573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '985534b682db'
down_revision: Union[str, None] = 'f1d75244863f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('path', sa.String(), nullable=True))
    op.drop_column('reports', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('reports', 'path')
    # ### end Alembic commands ###
