"""fix model message

Revision ID: aa19bc6c5da2
Revises: 37a0d4a9535c
Create Date: 2023-11-22 22:19:14.685463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa19bc6c5da2'
down_revision: Union[str, None] = '37a0d4a9535c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_message',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='user_message_message_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_message_user_id_fkey')
    )
    # ### end Alembic commands ###
