"""add logos model

Revision ID: f1d75244863f
Revises: c310f6880a42
Create Date: 2023-11-21 21:27:23.826752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1d75244863f'
down_revision: Union[str, None] = 'c310f6880a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logos', sa.Column('path', sa.String(), nullable=True))
    op.drop_column('logos', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logos', sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('logos', 'path')
    # ### end Alembic commands ###
